//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlServerCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlServerCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ES.Storage.SqlServerCommands", typeof(SqlServerCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE[dbo].[Events](
        ///	[Id]
        ///        [bigint] IDENTITY(1,1) NOT NULL,
        ///
        ///   [Timestamp] [timestamp]
        ///        NOT NULL,
        ///
        ///   [EventType] [varchar](250) NOT NULL,
        ///
        ///[Data] [varbinary](max) NOT NULL,
        ///
        ///[EntityId] [uniqueidentifier]
        ///        NOT NULL,
        ///CONSTRAINT[PK_Events] PRIMARY KEY CLUSTERED
        ///(
        ///[Id] ASC
        ///)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
        ///) ON[PRIMARY] TEXTIMAGE_ON[PRIMARY].
        /// </summary>
        internal static string CreateTableCommand {
            get {
                return ResourceManager.GetString("CreateTableCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Events]
        ///           ([EventType]
        ///           ,[Data]
        ///           ,[EntityId])
        ///     VALUES
        ///           (@eventType
        ///           ,@data
        ///           ,@entityId).
        /// </summary>
        internal static string InsertCommand {
            get {
                return ResourceManager.GetString("InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Timestamp]
        ///      ,[EventType]
        ///      ,[Data]
        ///      ,[EntityId]
        ///  FROM [dbo].[Events]
        ///  WHERE  [EntityId] = @entityId.
        /// </summary>
        internal static string SelectByEntity {
            get {
                return ResourceManager.GetString("SelectByEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Timestamp]
        ///      ,[EventType]
        ///      ,[Data]
        ///      ,[EntityId]
        ///  FROM [dbo].[Events]
        ///  WHERE [EventType] = @eventType and [EntityId] = @entityId.
        /// </summary>
        internal static string SelectByEntityAndEventTypeQuery {
            get {
                return ResourceManager.GetString("SelectByEntityAndEventTypeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
        ///           WHERE TABLE_NAME = N&apos;Events&apos;)
        ///BEGIN
        ///  SELECT 1;
        ///END.
        /// </summary>
        internal static string TableExistsQuery {
            get {
                return ResourceManager.GetString("TableExistsQuery", resourceCulture);
            }
        }
    }
}
